/*
 * Jakefile
 * CoreData
 *
 * Created by Raphael Bartolome on February 5, 2010.
 * 
 * The MIT License
 * 
 * Copyright (c) 2009 Raphael Bartolome
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * 
 */

var ENV = require("system").env,
    FILE = require("file"),
    OS = require("os"),
    JAKE = require("jake"),
    task = JAKE.task,
    FileList = JAKE.FileList,
    CLEAN = require("jake/clean").CLEAN,
    stream = require("narwhal/term").stream,
    framework = require("objective-j/jake").framework,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Release";

framework ("CoreData", function(task)
{   
    task.setBuildIntermediatesPath(FILE.join("Build", "CoreData.build", configuration));
    task.setBuildPath(FILE.join("Build", configuration));

    task.setProductName("CoreData");
    task.setIdentifier("com.rbartolome.CoreData");
    task.setVersion("0.1");
    task.setAuthor("Raphael Bartolome");
    task.setEmail("raphael.bartolome@gmail.com");
    task.setSummary("A CoreData implementation in Objective-J for Cappuccino");
    task.setSources(new FileList("**/*.j").exclude('Build/**/*'));
    task.setResources(new FileList("Resources/**/*"));
    task.setFlattensSources(true);
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["CoreData"]);

task ("build", ["default"]);

task ("debug", function()
{
    ENV["CONFIGURATION"] = "Debug";
    JAKE.subjake(["."], "build", ENV);
});

task ("release", function()
{
    ENV["CONFIGURATION"] = "Release";
    JAKE.subjake(["."], "build", ENV);
});


$BUILD_DIR = FILE.join("Build");
$BUILD_CJS_COREDATA = FILE.join($BUILD_DIR, "CommonJS");
$BUILD_COREDATA_DEBUG_FRAMEWORKS = FILE.join($BUILD_CJS_COREDATA, "Frameworks", "Debug");
$BUILD_COREDATA_RELEASE_FRAMEWORKS = FILE.join($BUILD_CJS_COREDATA, "Frameworks");


task ("install", ["release", "debug"], function()
{
    FILE.mkdirs($BUILD_COREDATA_RELEASE_FRAMEWORKS);
    cp_r(FILE.join($BUILD_DIR, "Release", "CoreData"), $BUILD_COREDATA_RELEASE_FRAMEWORKS);
    FILE.mkdirs($BUILD_COREDATA_DEBUG_FRAMEWORKS);
    cp_r(FILE.join($BUILD_DIR, "Debug", "CoreData"), $BUILD_COREDATA_DEBUG_FRAMEWORKS);
    // copy package.json
    FILE.copy(FILE.join("package.json"), FILE.join($BUILD_CJS_COREDATA, "package.json"));
    // metadata for package.json
    setPackageMetadata(FILE.join("package.json"));
    // install into narwhal
    if (OS.system(["tusk", "install", "--force", $BUILD_CJS_COREDATA]))
    {
        stream.print("\0red(Installation failed, possibly because you do not have permissions.\0)");
        stream.print("\0red(Try re-running using '\0yellow(jake sudo-install\0)'.\0)");
        OS.exit(1); //rake abort if ($? != 0)
    }
});

CLEAN.include(FILE.join("Build", "CoreData.build"));


global.getCoreDataVersion = function() {
    var versionFile = FILE.path(module.path).dirname().join("version.json");
    return JSON.parse(versionFile.read({ charset : "UTF-8" })).version;
}


setPackageMetadata = function(packagePath) {
    var pkg = JSON.parse(FILE.read(packagePath, { charset : "UTF-8" }));

    var p = OS.popen(["git", "rev-parse", "--verify", "HEAD"]);
    if (p.wait() === 0) {
        var sha = p.stdout.read().split("\n")[0];
        if (sha.length === 40)
            pkg["cappuccino-revision"] = sha;
    }

    pkg["cappuccino-timestamp"] = new Date().getTime();
    pkg["version"] = getCoreDataVersion();

    stream.print("    Version:   \0purple(" + pkg["version"] + "\0)");
    stream.print("    Revision:  \0purple(" + pkg["cappuccino-revision"] + "\0)");
    stream.print("    Timestamp: \0purple(" + pkg["cappuccino-timestamp"] + "\0)");

    FILE.write(packagePath, JSON.stringify(pkg, null, 4), { charset : "UTF-8" });
}


global.rm_rf = function(/*String*/ aFilename)
{
    try
    {
        FILE.rmtree(aFilename);
    } catch (anException)
    { }
}

global.cp_r = function(/*String*/ from, /*String*/ to)
{
    if (FILE.exists(to))
        rm_rf(to);

    if (FILE.isDirectory(from))
        FILE.copyTree(from, to);
    else
    {
        try
        {
            FILE.copy(from, to);
        } catch(e)
        {
            print(e + FILE.exists(from) + " " + FILE.exists(FILE.dirname(to)));
        }
    }
}

